// <auto-generated />
using System;
using System.Text.Json;
using CodeSwitchLabel.Repositories.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeSwitchLabel.Repositories.Persistence.Migrations
{
    [DbContext(typeof(CodeSwitchLabelDbContext))]
    [Migration("20260915074403_ReviewSelfReviewGuard")]
    partial class ReviewSelfReviewGuard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.AppUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("UserId")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_app_user_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_app_user_role");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_type");

                    b.Property<JsonDocument>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<JsonDocument>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("AuditId", "ChangedAt")
                        .HasName("pk_audit_log");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entity");

                    b.HasIndex("UserId", "ChangedAt")
                        .HasDatabaseName("ix_audit_user");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Dataset", b =>
                {
                    b.Property<long>("DatasetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dataset_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DatasetId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatasetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dataset_name");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("FileFormat")
                        .HasColumnType("integer")
                        .HasColumnName("file_format");

                    b.Property<string>("FileKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_key");

                    b.Property<JsonDocument>("FilterCriteria")
                        .HasColumnType("jsonb")
                        .HasColumnName("filter_criteria");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<long?>("ReleasedById")
                        .HasColumnType("bigint")
                        .HasColumnName("released_by_id");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("DatasetId")
                        .HasName("pk_dataset");

                    b.HasIndex("FileKey")
                        .IsUnique()
                        .HasDatabaseName("ux_dataset_file_key");

                    b.HasIndex("ReleasedById")
                        .HasDatabaseName("ix_dataset_released_by");

                    b.HasIndex("DatasetName", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_dataset_name_version");

                    b.ToTable("dataset", null, t =>
                        {
                            t.HasCheckConstraint("ck_dataset_release", "status <> 1 OR (released_by_id IS NOT NULL AND released_at IS NOT NULL AND file_key IS NOT NULL)");

                            t.HasCheckConstraint("ck_dataset_row_count", "row_count >= 0");
                        });
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.DatasetRecording", b =>
                {
                    b.Property<long>("DatasetId")
                        .HasColumnType("bigint")
                        .HasColumnName("dataset_id");

                    b.Property<long>("RecordingId")
                        .HasColumnType("bigint")
                        .HasColumnName("recording_id");

                    b.Property<DateTimeOffset>("IncludedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("included_at");

                    b.HasKey("DatasetId", "RecordingId")
                        .HasName("pk_dataset_recording");

                    b.HasIndex("RecordingId")
                        .HasDatabaseName("ix_dataset_recording_recording");

                    b.ToTable("dataset_recording", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.ImportBatch", b =>
                {
                    b.Property<long>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BatchId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("ImportedById")
                        .HasColumnType("bigint")
                        .HasColumnName("imported_by_id");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("BatchId")
                        .HasName("pk_import_batch");

                    b.HasIndex("ImportedById")
                        .HasDatabaseName("ix_import_batch_imported_by_id");

                    b.ToTable("import_batch", null, t =>
                        {
                            t.HasCheckConstraint("ck_import_batch_row_count", "row_count >= 0");
                        });
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipient_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("NotificationId")
                        .HasName("pk_notification");

                    b.HasIndex("RecipientId", "CreatedAt")
                        .HasDatabaseName("ix_notification_unread")
                        .HasFilter("read_at IS NULL");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Recording", b =>
                {
                    b.Property<long>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("recording_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordingId"));

                    b.Property<string>("AudioFormat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("wav")
                        .HasColumnName("audio_format");

                    b.Property<decimal>("DurationSec")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("duration_sec");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("s3_key");

                    b.Property<long>("ScriptId")
                        .HasColumnType("bigint")
                        .HasColumnName("script_id");

                    b.Property<long>("SpeakerId")
                        .HasColumnType("bigint")
                        .HasColumnName("speaker_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.HasKey("RecordingId")
                        .HasName("pk_recording");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_recording_pending")
                        .HasFilter("status = 1");

                    b.HasIndex("S3Key")
                        .IsUnique()
                        .HasDatabaseName("ux_recording_s3_key");

                    b.HasIndex("ScriptId")
                        .HasDatabaseName("ix_recording_script");

                    b.HasIndex("SpeakerId")
                        .HasDatabaseName("ix_recording_speaker");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_recording_task");

                    b.ToTable("recording", null, t =>
                        {
                            t.HasCheckConstraint("ck_recording_duration", "duration_sec > 0");
                        });
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.RejectionReason", b =>
                {
                    b.Property<short>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("reason_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("ReasonId"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason_code");

                    b.HasKey("ReasonId")
                        .HasName("pk_rejection_reason");

                    b.HasIndex("ReasonCode")
                        .IsUnique()
                        .HasDatabaseName("ux_rejection_reason_code");

                    b.ToTable("rejection_reason", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Review", b =>
                {
                    b.Property<long>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<bool>("IsBlind")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blind");

                    b.Property<long>("RecordingId")
                        .HasColumnType("bigint")
                        .HasColumnName("recording_id");

                    b.Property<short>("ReviewRound")
                        .HasColumnType("smallint")
                        .HasColumnName("review_round");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<long>("ReviewerId")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewer_id");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.HasKey("ReviewId")
                        .HasName("pk_review");

                    b.HasIndex("RecordingId")
                        .HasDatabaseName("ix_review_rejected")
                        .HasFilter("decision = 1");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("ix_review_reviewer");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_review_task");

                    b.HasIndex("RecordingId", "ReviewerId", "ReviewRound")
                        .IsUnique()
                        .HasDatabaseName("ux_review_recording_reviewer_round");

                    b.ToTable("review", null, t =>
                        {
                            t.HasCheckConstraint("ck_review_round", "review_round BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.ReviewRejectionReason", b =>
                {
                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    b.Property<short>("ReasonId")
                        .HasColumnType("smallint")
                        .HasColumnName("reason_id");

                    b.HasKey("ReviewId", "ReasonId")
                        .HasName("pk_review_rejection_reason");

                    b.HasIndex("ReasonId")
                        .HasDatabaseName("ix_review_rejection_reason_reason");

                    b.ToTable("review_rejection_reason", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Role", b =>
                {
                    b.Property<short>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("pk_role");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("ux_role_name");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Script", b =>
                {
                    b.Property<long>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("script_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScriptId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<int>("Domain")
                        .HasColumnType("integer")
                        .HasColumnName("domain");

                    b.Property<int>("EnWordCount")
                        .HasColumnType("integer")
                        .HasColumnName("en_word_count");

                    b.Property<long?>("ImportBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("import_batch_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("ScriptId")
                        .HasName("pk_script");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_script_pending")
                        .HasFilter("status = 0");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_script_created_by");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("ix_script_import_batch_id");

                    b.HasIndex("Status", "Domain")
                        .HasDatabaseName("ix_script_status_domain");

                    b.ToTable("script", null, t =>
                        {
                            t.HasCheckConstraint("ck_script_en_not_exceed_total", "en_word_count <= word_count");

                            t.HasCheckConstraint("ck_script_en_word_count", "en_word_count >= 0");

                            t.HasCheckConstraint("ck_script_word_count", "word_count >= 0");
                        });
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.ScriptErrorReason", b =>
                {
                    b.Property<short>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("reason_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("ReasonId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("ReasonId")
                        .HasName("pk_script_error_reason");

                    b.HasIndex("ReasonCode")
                        .IsUnique()
                        .HasDatabaseName("ux_script_error_reason_code");

                    b.ToTable("script_error_reason", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.ScriptReview", b =>
                {
                    b.Property<long>("ScriptReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("script_review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScriptReviewId"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<string>("EditedContent")
                        .HasColumnType("text")
                        .HasColumnName("edited_content");

                    b.Property<short?>("ErrorReasonId")
                        .HasColumnType("smallint")
                        .HasColumnName("error_reason_id");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<long>("ScriptId")
                        .HasColumnType("bigint")
                        .HasColumnName("script_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ScriptReviewId")
                        .HasName("pk_script_review");

                    b.HasIndex("ErrorReasonId")
                        .HasDatabaseName("ix_script_review_error_reason_id");

                    b.HasIndex("ScriptId")
                        .HasDatabaseName("ix_script_review_script");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_script_review_user");

                    b.ToTable("script_review", null, t =>
                        {
                            t.HasCheckConstraint("ck_script_review_edited", "(action = 1) = (edited_content IS NOT NULL)");

                            t.HasCheckConstraint("ck_script_review_reason", "action <> 2 OR error_reason_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.ScriptSkip", b =>
                {
                    b.Property<long>("SkipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("skip_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SkipId"));

                    b.Property<long>("ScriptId")
                        .HasColumnType("bigint")
                        .HasColumnName("script_id");

                    b.Property<DateTimeOffset>("SkippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("skipped_at");

                    b.Property<long>("SpeakerId")
                        .HasColumnType("bigint")
                        .HasColumnName("speaker_id");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.HasKey("SkipId")
                        .HasName("pk_script_skip");

                    b.HasIndex("SpeakerId")
                        .HasDatabaseName("ix_script_skip_speaker_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_script_skip_task_id");

                    b.HasIndex("ScriptId", "SpeakerId")
                        .IsUnique()
                        .HasDatabaseName("ux_script_skip_speaker");

                    b.ToTable("script_skip", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.SpeakerProfile", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<int?>("EnglishLevel")
                        .HasColumnType("integer")
                        .HasColumnName("english_level");

                    b.Property<int?>("Occupation")
                        .HasColumnType("integer")
                        .HasColumnName("occupation");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<int?>("Region")
                        .HasColumnType("integer")
                        .HasColumnName("region");

                    b.HasKey("UserId")
                        .HasName("pk_speaker_profile");

                    b.ToTable("speaker_profile", null, t =>
                        {
                            t.HasCheckConstraint("ck_speaker_profile_birth_year", "birth_year IS NULL OR (birth_year >= 1900 AND birth_year <= EXTRACT(YEAR FROM now()))");
                        });
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.SystemConfig", b =>
                {
                    b.Property<short>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("config_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("ConfigId"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer")
                        .HasColumnName("value_type");

                    b.HasKey("ConfigId")
                        .HasName("pk_system_config");

                    b.HasIndex("ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("ux_system_config_key");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_system_config_updated_by_id");

                    b.ToTable("system_config", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.TaskAssignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AssignmentId"));

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int>("AssignmentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_status");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("AssignmentId")
                        .HasName("pk_task_assignment");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasDatabaseName("ux_task_active_assignment")
                        .HasFilter("assignment_status = 0");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_task_assignment_user");

                    b.ToTable("task_assignment", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.TaskRecording", b =>
                {
                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<long>("RecordingId")
                        .HasColumnType("bigint")
                        .HasColumnName("recording_id");

                    b.Property<DateTimeOffset>("IncludedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("included_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("TaskId", "RecordingId")
                        .HasName("pk_task_recording");

                    b.HasIndex("RecordingId")
                        .HasDatabaseName("ix_task_recording_recording");

                    b.ToTable("task_recording", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.TaskScript", b =>
                {
                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<long>("ScriptId")
                        .HasColumnType("bigint")
                        .HasColumnName("script_id");

                    b.Property<DateTimeOffset>("IncludedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("included_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("TaskId", "ScriptId")
                        .HasName("pk_task_script");

                    b.HasIndex("ScriptId")
                        .HasDatabaseName("ix_task_script_script");

                    b.ToTable("task_script", (string)null);
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.WorkTask", b =>
                {
                    b.Property<long>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TaskId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TargetQty")
                        .HasColumnType("integer")
                        .HasColumnName("target_qty");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer")
                        .HasColumnName("task_type");

                    b.HasKey("TaskId")
                        .HasName("pk_task");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_task_created_by");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("ix_task_open_deadline")
                        .HasFilter("status IN (1, 2)");

                    b.ToTable("task", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_target_qty", "target_qty > 0");
                        });
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.AppUser", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_role_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.AuditLog", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_log_app_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Dataset", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "ReleasedBy")
                        .WithMany()
                        .HasForeignKey("ReleasedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_dataset_app_user_released_by_id");

                    b.Navigation("ReleasedBy");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.DatasetRecording", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.Dataset", "Dataset")
                        .WithMany("Recordings")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dataset_recording_dataset_dataset_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.Recording", "Recording")
                        .WithMany("DatasetRecordings")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dataset_recording_recording_recording_id");

                    b.Navigation("Dataset");

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.ImportBatch", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "ImportedBy")
                        .WithMany()
                        .HasForeignKey("ImportedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_import_batch_app_user_imported_by_id");

                    b.Navigation("ImportedBy");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Notification", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_app_user_recipient_id");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Recording", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.Script", "Script")
                        .WithMany("Recordings")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recording_script_script_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "Speaker")
                        .WithMany()
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recording_app_user_speaker_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.WorkTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recording_task_task_id");

                    b.Navigation("Script");

                    b.Navigation("Speaker");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Review", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.Recording", "Recording")
                        .WithMany("Reviews")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_recording_recording_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_app_user_reviewer_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.WorkTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_review_task_task_id");

                    b.Navigation("Recording");

                    b.Navigation("Reviewer");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.ReviewRejectionReason", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.RejectionReason", "Reason")
                        .WithMany("Reviews")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_rejection_reason_rejection_reason_reason_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.Review", "Review")
                        .WithMany("RejectionReasons")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_rejection_reason_review_review_id");

                    b.Navigation("Reason");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Script", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_script_app_user_created_by_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Scripts")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_script_import_batch_import_batch_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.ScriptReview", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.ScriptErrorReason", "ErrorReason")
                        .WithMany("ScriptReviews")
                        .HasForeignKey("ErrorReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_script_review_script_error_reason_error_reason_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.Script", "Script")
                        .WithMany("Reviews")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_script_review_script_script_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_script_review_app_user_user_id");

                    b.Navigation("ErrorReason");

                    b.Navigation("Script");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.ScriptSkip", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.Script", "Script")
                        .WithMany("Skips")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_script_skip_script_script_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "Speaker")
                        .WithMany()
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_script_skip_app_user_speaker_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.WorkTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_script_skip_task_task_id");

                    b.Navigation("Script");

                    b.Navigation("Speaker");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.SpeakerProfile", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "User")
                        .WithOne("SpeakerProfile")
                        .HasForeignKey("CodeSwitchLabel.Repositories.Entities.SpeakerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_speaker_profile_app_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.SystemConfig", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_system_config_app_user_updated_by_id");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.TaskAssignment", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.WorkTask", "Task")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_assignment_task_task_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_assignment_app_user_user_id");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.TaskRecording", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.Recording", "Recording")
                        .WithMany("TaskRecordings")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_recording_recording_recording_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.WorkTask", "Task")
                        .WithMany("TaskRecordings")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_recording_task_task_id");

                    b.Navigation("Recording");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.TaskScript", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.Script", "Script")
                        .WithMany("TaskScripts")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_script_script_script_id");

                    b.HasOne("CodeSwitchLabel.Repositories.Entities.WorkTask", "Task")
                        .WithMany("TaskScripts")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_script_task_task_id");

                    b.Navigation("Script");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.WorkTask", b =>
                {
                    b.HasOne("CodeSwitchLabel.Repositories.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_app_user_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.AppUser", b =>
                {
                    b.Navigation("SpeakerProfile");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Dataset", b =>
                {
                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.ImportBatch", b =>
                {
                    b.Navigation("Scripts");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Recording", b =>
                {
                    b.Navigation("DatasetRecordings");

                    b.Navigation("Reviews");

                    b.Navigation("TaskRecordings");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.RejectionReason", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Review", b =>
                {
                    b.Navigation("RejectionReasons");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.Script", b =>
                {
                    b.Navigation("Recordings");

                    b.Navigation("Reviews");

                    b.Navigation("Skips");

                    b.Navigation("TaskScripts");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.ScriptErrorReason", b =>
                {
                    b.Navigation("ScriptReviews");
                });

            modelBuilder.Entity("CodeSwitchLabel.Repositories.Entities.WorkTask", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("TaskRecordings");

                    b.Navigation("TaskScripts");
                });
#pragma warning restore 612, 618
        }
    }
}
